
timeout: 3
default_entry: 2
remember_last_entry: yes

/+Arch Linux
  //Arch Linux
    protocol: inux
    path: boot():/vmlinuz-linux
    module_path: boot():/initramfs-linux.img
    cmdline: quiet splash
  //Arch Linux (LTS)
    protocol: linux
    path: boot():/vmlinuz-linux-lts
    module_path: boot():/initramfs-linux-lts.img
    cmdline: quiet splash
