
timeout: 3
default_entry: 2
remember_last_entry: yes

/+Arch Linux
  //Arch Linux
    protocol: inux
    path(): boot():/TODO
    module_path(): boot():/TODO
    cmdline: quiet splash
  //Arch Linux (LTS)
    protocol: linux
    path(): boot():/TODO
    module_path(): boot():/TODO
    cmdline: quiet splash
